---

db_hostname: "{{ hostvars[groups['db_server'][0]]['inventory_hostname'] }}"
scm_hostname: "{{ hostvars[groups['scm_server'][0]]['inventory_hostname'] }}"

cluster_display_name: "{{ lookup('env', 'SCM_CLUSTER_DISPLAY_NAME') | default('cluster_1') }}""

cdh_services:

  - type: hbase

  - type: hdfs
    dfs_data_dir_list: "{{ clusterdef[cluster_display_name].hdfs.dfs_data_dir_list }}"
    fs_checkpoint_dir_list: "{{ clusterdef[cluster_display_name].hdfs.fs_checkpoint_dir_list }}"
    dfs_name_dir_list: "{{ clusterdef[cluster_display_name].hdfs.dfs_name_dir_list }}"
    dfs_journalnode_edits_dir: "{{ clusterdef[cluster_display_name].hdfs.dfs_journalnode_edits_dir }}"
    autofailover_enabled: "{{ clusterdef.dynamic.hdfs.autofailover_enabled | default(clusterdef[cluster_display_name].hdfs.autofailover_enabled) }}"

  - type: kudu
    m_fs_data_dirs: "/var/lib/kudu/master"
    m_fs_wal_dir: "/var/lib/kudu/master"
    t_fs_data_dirs: "/var/lib/kudu/tserver"
    t_fs_wal_dir: "/var/lib/kudu/tserver"

  - type: hive

  - type: hue

  - type: impala
    scratch_dirs: /tmp/impala

  - type: oozie

  - type: sentry

  - type: spark

  - type: yarn
    yarn_nodemanager_local_dirs: /tmp/nm
    yarn_nodemanager_log_dirs: /var/log/nm

  - type: zookeeper
