---
# Cloudera playbook
- name: Generate parcels archives to be used by install parcels tasks
  hosts: localhost
  connection: local
  become: yes
  roles:
    - tarball_parcels
  tags:
    - tarball_parcels
    - custom_repo

- name: Prefetch packages repo-as-tarball locally
  hosts: localhost
  connection: local
  become: yes
  roles:
    - prefetch_packages
  tags:
    - prefetch_packages
    - custom_repo

- name: Install custom parcel repository
  hosts: custom_repo
  become: yes
  roles:
    - custom_repo
  tags:
    - custom_repo

- name: Preload parcels from custom repo to Cloudera Manager
  hosts: scm_server
  become: yes
  gather_facts: no
  roles:
    - role: preload_parcels
      when: "'custom_repo' in groups"
  tags:
    - preload_parcels

- name: Configure Cloudera Manager Repository
  hosts: cdh_servers
  roles:
    - cm_repo
  tags: cm_repo

- name: Install rngd
  hosts: cdh_servers
  roles:
    - rngd
  tags: rngd

- name: Install Java
  hosts: cdh_servers
  roles:
    - java
  tags: java

- name: Install MariaDB and create databases
  hosts: db_server
  roles:
    - mariadb
  tags:
    - mysql
    - mysql_server

- name: Install MySQL Connector
  hosts: cdh_servers
  roles:
    - mysql_connector
  tags:
    - mysql
    - mysql_client

- name: Install MIT KDC Server
  hosts: krb5_server
  roles:
    - krb5/server
  tags: krb5

- name: Install MIT KDC Client
  hosts: all
  roles:
    - { role: krb5/client, when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none') }
  tags:
    - krb5
    - krb5_client

- name: Configure EPEL Repository
  hosts: scm_server
  roles:
    - epel
  tags: epel

- name: Install Cloudera Manager Agents
  hosts: cdh_servers
  roles:
    - cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - scm
  tags: cluster_template

- name: Install CDH
  hosts: scm_server
  roles:
    - cdh
  tags: cluster_template

