# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure tmp repo directories exist for file downloads
  loop: "{{ custom_repo_rehost_files }}"
  loop_control:
    loop_var: __tmp_local_package_dir_item
  ansible.builtin.file:
    path: "{{ local_temp_dir }}{{ __tmp_local_package_dir_item | urlsplit('path') | dirname }}"
    state: directory

- name: Request Async Download of files to tmp dir
  register: __infra_download_parcels_results
  loop: "{{ custom_repo_rehost_files }}"
  loop_control:
    loop_var: __repo_as_tarball_download_item
  async: 3600
  poll: 0
  ansible.builtin.get_url:
    url: "{{ __repo_as_tarball_download_item }}"
    dest: "{{ local_temp_dir }}{{ __repo_as_tarball_download_item | urlsplit('path') }}"

- name: Track async downloads to completion  [ This may take a while if your files are very large or far away ]
  loop: "{{ __infra_download_parcels_results.results }}"
  loop_control:
    loop_var: __download_async_item
  register: __async_download_results
  until: __async_download_results.finished is defined and __async_download_results.finished
  delay: 15
  retries: 300
  async_status:
    jid: "{{ __download_async_item.ansible_job_id }}"
  failed_when:
    - __download_async_item.failed == True
    - __download_async_item.finished != 1
