---

- name: Prepare dynamic clusterdef layer
  set_fact:
    dynamic_output: "{{ lookup('template', 'dynamic.j2') }}"

- name: Assert no errors present on dynamic layer output
  assert:
    that:
      - dynamic_output.errors | dict2items | length == 0
    fail_msg: "{{ dynamic_output.errors | to_json }}"
    quiet: true
  
# Dynamic insights override if needed cdh_servers services' settings
- name: Overlay clusterdef with dynamic insights
  set_fact:
    clusterdef: "{{ dynamic_output.clusterdef }}"

- include_vars: ../../../group_vars/cdh_servers.yml
- include_vars: ../../../group_vars/db_server.yml

- name: Dynamic overlay of CDH servers services
  block:
    - set_fact:
        host_templates: "{{ lookup('template', 'host.j2') }}"
    - debug: var=host_templates
    - set_fact:
        host_templates_rquested: "{{ groups['cdh_servers'] | map('extract', hostvars) | selectattr('host_template', 'defined') | map(attribute='host_template') | unique | list }}"
    - debug: var=host_templates_rquested
    - set_fact:
        rcg_ref_names_requested: "{{ host_templates_rquested | map('extract', dict((host_templates | map(attribute='refName')) | zip(host_templates)), 'roleConfigGroupsRefNames') | flatten | unique | list }}"
    - debug: var=rcg_ref_names_requested
    - set_fact:
        updated_cdh_services: "{{ updated_cdh_services | default([]) | union({item}) }}"
      when: rcg_ref_names_requested | regex_findall("(?i)" ~ item.type) | length > 0
      loop: "{{ cdh_services }}"
    - debug: var=updated_cdh_services
    - set_fact:
        cdh_services: "{{ updated_cdh_services }}"

# Check whether cluster already exists
# https://cloudera.github.io/cm_api/apidocs/v13/path__clusters.html
- name: Check whether cluster exists
  uri:
    url: "{{ cm_api_url }}/clusters/{{ cluster_display_name }}"
    method: GET
    status_code: 200,404
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: clusters_resp

- set_fact:
    cluster_exists: "{{ 'True' if clusters_resp.status == 200 else 'False' }}"

- debug:
    msg: "Cluster '{{ cluster_display_name }}' exists - {{ cluster_exists }}"
    verbosity: 1

- name: Discover product versions from parcel manifests
  uri:
    url: "{{ item }}/manifest.json"
    status_code: 200
    body_format: json
    return_content: yes
  register: manifests
  with_items: 
    - "{{ scm_parcel_repositories }}"

- set_fact:
    scm_products: "{{ manifests.results | map(attribute='json') | list | json_query('[*].parcels[0].parcelName') | map('regex_replace', '-[a-z0-9]+.parcel$','') | list }}"

# https://www.cloudera.com/documentation/enterprise/latest/topics/install_cluster_template.html
- set_fact:
    cluster_template_json: "{{ lookup('template', 'base.j2', convert_data=False) }}"
  when: not cluster_exists

- debug:
    var: cluster_template_json
    verbosity: 1

# https://cloudera.github.io/cm_api/apidocs/v13/path__cm_importClusterTemplate.html
- name: Import cluster template
  uri:
    url: "{{ cm_api_url }}/cm/importClusterTemplate?addRepositories=true"
    method: POST
    body_format: json
    body: "{{ cluster_template_json|to_json }}"
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: template_resp
  when: not cluster_exists

- debug:
    var: template_resp
    verbosity: 1
  when: not cluster_exists

- set_fact:
    command_id: "{{ template_resp.json.id }}"
  when: not cluster_exists

- debug:
    msg: "Login to Cloudera Manager to monitor import progress - http://{{ hostvars[scm_hostname]['inventory_hostname'] }}:{{ scm_port }}/cmf/command/{{ command_id }}/details"
    verbosity: 1
  when: not cluster_exists

- name: Wait for import cluster template command to complete
  uri: 
    url: "{{ cm_api_url }}/commands/{{ command_id }}"
    body_format: json
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: result
  until: not result.json.active
  retries: 10
  delay: 60
  when: not cluster_exists
  failed_when: "'Failed to import cluster template' in result.content"

- debug:
    var: result
  when: not cluster_exists

- name: Restart Cloudera Management Service
  uri:
    url: "{{ cm_api_url }}/cm/service/commands/restart"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: start_resp
  failed_when: "'startTime' not in start_resp.content"
  when: not cluster_exists
